# -*- coding: utf-8 -*-
"""SpikeLoRA-X - CAEPEA 2026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5F4O43YENWBZSp8frDzWcP6ZqMO5_0X
"""

# ===============================
# SpikeLoRA-X Full Colab Notebook - Fully Executable
# Includes all models, training utilities, E1/E2/E3 experiments, plotting, CSV/PNG export
# Copy-paste into Colab and run cell by cell
# ===============================

# -------------------------------
# Cell 0: Install dependencies
# -------------------------------
!pip install torch torchvision torchaudio
!pip install spikingjelly
!pip install numpy pandas scikit-learn tqdm matplotlib

# -------------------------------
# Cell 1: Imports & Config
# -------------------------------
import os, time, random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import spikingjelly
from spikingjelly.activation_based import neuron, surrogate, functional

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('Using device:', device)

random.seed(0)
np.random.seed(0)
torch.manual_seed(0)
torch.cuda.manual_seed_all(0)

# ===============================
# Cell 2: Dataset Loader + Windowing + Splits
# Restored from the better old procedure
# ===============================

import pandas as pd
import numpy as np
from torch.utils.data import Dataset

# ===============================
# FIXED Dataset Loader
# Explicit target variables for each task
# ===============================

import pandas as pd
import numpy as np

DATASETS = {
    "SR": {
        "path": "Palestine-Solar.csv",
        "time_col": "date",
        "target_col": "GHI",
    },
    "WS": {
        "path": "Palestine-wind.csv",
        "time_col": "date",
        # This will match either "Wind Speed" or "Wind Speed (m/s)"
        "target_col": "Wind Speed",
    },
    "WP": {
        "path": "Turky-Wind-power-Turbine.csv",
        "time_col": "date",
        "target_col": "LV ActivePower (kW)",
    },
    "EC": {
        "path": "Moroco-power-consumption.csv",
        "time_col": "Date",
        "target_col": "PowerConsumption_Zone1",
    },
}


def _guess_time_col(df: pd.DataFrame) -> str:
    for c in ["date", "Date", "datetime", "Datetime", "timestamp", "Timestamp", "time", "Time", "Date/Time"]:
        if c in df.columns:
            return c
    return df.columns[0]


def _normalize_colname(s):
    """
    Normalize a column name for robust matching.
    Removes spaces, underscores, slashes, brackets, degree symbols, and units.
    """
    s = str(s).lower()
    for token in ["_", " ", "/", "-", "(", ")", "[", "]", "°"]:
        s = s.replace(token, "")
    return s


def _find_column_case_insensitive(df, desired_col):
    """
    Robust column finder.

    Matching priority:
    1. Exact match.
    2. Normalized exact match.
    3. Desired name contained inside actual column name.
       Example: 'Wind Speed' -> 'Wind Speed (m/s)'.
    4. Actual column contained inside desired name.
    """

    if desired_col in df.columns:
        return desired_col

    desired_norm = _normalize_colname(desired_col)

    # Normalized exact match
    for c in df.columns:
        if _normalize_colname(c) == desired_norm:
            return c

    # Desired inside actual
    for c in df.columns:
        c_norm = _normalize_colname(c)
        if desired_norm in c_norm:
            return c

    # Actual inside desired
    for c in df.columns:
        c_norm = _normalize_colname(c)
        if c_norm in desired_norm:
            return c

    raise ValueError(
        f"Column '{desired_col}' not found. Available columns are:\n{list(df.columns)}"
    )

def load_df(task_id: str):
    cfg = DATASETS[task_id]
    path = cfg["path"]

    df = pd.read_csv(path)

    # Explicit time/target with fallback matching
    time_col = cfg.get("time_col", None)
    target_col = cfg.get("target_col", None)

    if time_col is None:
        time_col = _guess_time_col(df)
    else:
        time_col = _find_column_case_insensitive(df, time_col)

    if target_col is None:
        raise ValueError(
            f"Target column must be explicitly defined for task {task_id}."
        )
    else:
        target_col = _find_column_case_insensitive(df, target_col)

    # Parse and sort by time
    df[time_col] = pd.to_datetime(df[time_col], errors="coerce")
    df = df.dropna(subset=[time_col]).sort_values(time_col).reset_index(drop=True)

    # Keep numeric feature columns only
    feat_cols = [
        c for c in df.columns
        if c != time_col and pd.api.types.is_numeric_dtype(df[c])
    ]

    if target_col not in feat_cols:
        raise ValueError(
            f"Target column '{target_col}' is not numeric or not in feature columns.\n"
            f"Numeric columns are:\n{feat_cols}"
        )

    df = df[[time_col] + feat_cols].copy()

    print(f"\n=== Dataset {task_id} ===")
    print(f"Path: {path}")
    print(f"Time column: {time_col}")
    print(f"Target variable: {target_col}")
    print(f"Shape: {df.shape}")

    return df, {
        "time_col": time_col,
        "target_col": target_col,
        "feat_cols": feat_cols
    }


def make_supervised(df, time_col, target_col, lookback, horizons, add_calendar=True):
    feat_cols = [c for c in df.columns if c != time_col]
    X_raw = df[feat_cols].values.astype(np.float32)

    if add_calendar:
        t = df[time_col]
        cal = np.stack([
            t.dt.hour.fillna(0).values,
            t.dt.dayofweek.fillna(0).values,
            t.dt.month.fillna(0).values,
        ], axis=1).astype(np.float32)

        cal[:, 0] /= 23.0
        cal[:, 1] /= 6.0
        cal[:, 2] /= 12.0

        X_raw = np.concatenate([X_raw, cal], axis=1)

    L = lookback
    max_h = max(horizons)

    X, Y = [], []

    for i in range(L, len(X_raw) - max_h):
        X.append(X_raw[i - L:i])
        Y.append([df[target_col].values[i + h].astype(np.float32) for h in horizons])

    return np.stack(X, axis=0), np.stack(Y, axis=0)


def chronological_split(X, Y, train_ratio=0.7, val_ratio=0.1):
    n = len(X)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)

    Xtr, Ytr = X[:n_train], Y[:n_train]
    Xva, Yva = X[n_train:n_train + n_val], Y[n_train:n_train + n_val]
    Xte, Yte = X[n_train + n_val:], Y[n_train + n_val:]

    return (Xtr, Ytr), (Xva, Yva), (Xte, Yte)


def standardize_fit_transform(Xtr, Xva, Xte):
    mu = Xtr.mean(axis=(0, 1), keepdims=True)
    sd = Xtr.std(axis=(0, 1), keepdims=True) + 1e-6

    Xtr_s = (Xtr - mu) / sd
    Xva_s = (Xva - mu) / sd
    Xte_s = (Xte - mu) / sd

    return Xtr_s, Xva_s, Xte_s, (mu, sd)


class WindowDataset(Dataset):
    def __init__(self, X, Y):
        self.X = X.astype(np.float32)
        self.Y = Y.astype(np.float32)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.Y[idx]
# -------------------------------
# Cell 3: Metrics
# -------------------------------
rmse_np = lambda y_true, y_pred: float(np.sqrt(np.mean((y_true-y_pred)**2)))
mae_np = lambda y_true, y_pred: float(np.mean(np.abs(y_true-y_pred)))
smape_np = lambda y_true, y_pred, eps=1e-8: float(200*np.mean(np.abs(y_pred-y_true)/(np.abs(y_true)+np.abs(y_pred)+eps)))

@torch.no_grad()
def eval_metrics(y_true_t, y_pred_t):
    y_true = y_true_t.detach().cpu().numpy()
    y_pred = y_pred_t.detach().cpu().numpy()
    return {'rmse': rmse_np(y_true,y_pred), 'mae': mae_np(y_true,y_pred), 'smape': smape_np(y_true,y_pred)}

# ===============================
# Cell 4: Model Definitions
# Restored stronger models from old SpikeLoRA-TS procedure
# ===============================

import math
import torch
import torch.nn as nn
import torch.nn.functional as F

from spikingjelly.activation_based import neuron, surrogate, functional


class MLPBaseline(nn.Module):
    def __init__(self, lookback, F, K, hidden=256, dropout=0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Flatten(),
            nn.Linear(lookback * F, hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, hidden),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden, K),
        )

    def forward(self, x):
        return self.net(x)


class RNNBaseline(nn.Module):
    def __init__(self, kind, F, K, hidden=128, layers=2, dropout=0.1):
        super().__init__()

        RNN = nn.LSTM if kind == "lstm" else nn.GRU

        self.rnn = RNN(
            input_size=F,
            hidden_size=hidden,
            num_layers=layers,
            batch_first=True,
            dropout=dropout if layers > 1 else 0.0
        )

        self.head = nn.Linear(hidden, K)

    def forward(self, x):
        out, _ = self.rnn(x)
        return self.head(out[:, -1])


class TCNBaseline(nn.Module):
    def __init__(self, F, K, channels=128, levels=3, k=3, dropout=0.1):
        super().__init__()

        layers = []
        in_ch = F

        for i in range(levels):
            dilation = 2 ** i
            pad = (k - 1) * dilation

            layers += [
                nn.Conv1d(in_ch, channels, kernel_size=k, dilation=dilation, padding=pad),
                nn.ReLU(),
                nn.Dropout(dropout),
            ]

            in_ch = channels

        self.net = nn.Sequential(*layers)
        self.head = nn.Linear(channels, K)

    def forward(self, x):
        z = x.transpose(1, 2)
        z = self.net(z)
        z = z[:, :, -1]
        return self.head(z)


class PatchTST(nn.Module):
    def __init__(
        self,
        F,
        K,
        patch_len=16,
        stride=8,
        d_model=128,
        nhead=4,
        layers=3,
        dropout=0.1
    ):
        super().__init__()

        self.patch_len = patch_len
        self.stride = stride

        self.proj = nn.Linear(patch_len * F, d_model)

        enc = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=4 * d_model,
            dropout=dropout,
            batch_first=True,
            activation="gelu",
            norm_first=True
        )

        self.tf = nn.TransformerEncoder(enc, num_layers=layers)
        self.head = nn.Sequential(
            nn.LayerNorm(d_model),
            nn.Linear(d_model, K)
        )

    def patchify(self, x):
        B, L, Fdim = x.shape
        patches = []

        for s in range(0, L - self.patch_len + 1, self.stride):
            patches.append(x[:, s:s + self.patch_len, :])

        return torch.stack(patches, dim=1)

    def forward(self, x):
        p = self.patchify(x)
        B, Np, Pl, Fdim = p.shape

        tok = p.reshape(B, Np, Pl * Fdim)
        z = self.proj(tok)

        h = self.tf(z)

        return self.head(h[:, -1])


class Chomp1d(nn.Module):
    def __init__(self, chomp_size: int):
        super().__init__()
        self.chomp_size = chomp_size

    def forward(self, x):
        if self.chomp_size == 0:
            return x
        return x[:, :, :-self.chomp_size].contiguous()


class TemporalBlock(nn.Module):
    def __init__(self, c_in, c_out, kernel=3, dilation=1, dropout=0.1):
        super().__init__()

        pad = (kernel - 1) * dilation

        self.conv1 = nn.utils.weight_norm(
            nn.Conv1d(
                c_in,
                c_out,
                kernel_size=kernel,
                stride=1,
                padding=pad,
                dilation=dilation
            )
        )
        self.chomp1 = Chomp1d(pad)
        self.relu1 = nn.ReLU()
        self.drop1 = nn.Dropout(dropout)

        self.conv2 = nn.utils.weight_norm(
            nn.Conv1d(
                c_out,
                c_out,
                kernel_size=kernel,
                stride=1,
                padding=pad,
                dilation=dilation
            )
        )
        self.chomp2 = Chomp1d(pad)
        self.relu2 = nn.ReLU()
        self.drop2 = nn.Dropout(dropout)

        self.downsample = nn.Conv1d(c_in, c_out, kernel_size=1) if c_in != c_out else None
        self.relu = nn.ReLU()

        nn.init.kaiming_normal_(self.conv1.weight)
        nn.init.kaiming_normal_(self.conv2.weight)

        if self.downsample is not None:
            nn.init.kaiming_normal_(self.downsample.weight)

    def forward(self, x):
        out = self.conv1(x)
        out = self.chomp1(out)
        out = self.relu1(out)
        out = self.drop1(out)

        out = self.conv2(out)
        out = self.chomp2(out)
        out = self.relu2(out)
        out = self.drop2(out)

        res = x if self.downsample is None else self.downsample(x)

        return self.relu(out + res)


class SpikeEncoder(nn.Module):
    def __init__(self, thr=0.05):
        super().__init__()
        self.thr = thr

    def forward(self, x):
        dx = x[:, 1:, :] - x[:, :-1, :]
        sp = (dx.abs() > self.thr).float()
        z0 = torch.zeros_like(x[:, :1, :])
        return torch.cat([z0, sp], dim=1)


class SpikingTCN(nn.Module):
    """
    Strong original SpikingTCN used in the old procedure.
    """

    def __init__(self, F, K, channels=(64, 64, 64), T=8, thr=1.0):
        super().__init__()

        self.T = T

        self.encoder = SpikeEncoder(thr=0.05)
        self.in_proj = nn.Linear(F, channels[0])

        self.lif = neuron.LIFNode(
            v_threshold=thr,
            surrogate_function=surrogate.Sigmoid(),
            detach_reset=True
        )

        blocks = []
        c_in = channels[0]

        for i, c_out in enumerate(channels):
            blocks.append(
                TemporalBlock(
                    c_in,
                    c_out,
                    kernel=3,
                    dilation=2 ** i,
                    dropout=0.1
                )
            )
            c_in = c_out

        self.tcn = nn.Sequential(*blocks)
        self.head = nn.Linear(c_in, K)

    def forward(self, x):
        functional.reset_net(self)

        spk = self.encoder(x)

        acc = 0.0

        for _ in range(self.T):
            z = self.in_proj(spk)
            s = self.lif(z)
            h = self.tcn(s.transpose(1, 2))[:, :, -1]
            acc = acc + self.head(h)

        return acc / self.T


class LoRALinear(nn.Module):
    def __init__(self, base: nn.Linear, r=8, alpha=16, dropout=0.0):
        super().__init__()

        self.base = base
        self.r = r
        self.alpha = alpha
        self.scale = alpha / r
        self.drop = nn.Dropout(dropout)

        in_dim = base.in_features
        out_dim = base.out_features

        self.A = nn.Parameter(torch.zeros(r, in_dim))
        self.B = nn.Parameter(torch.zeros(out_dim, r))

        nn.init.kaiming_uniform_(self.A, a=math.sqrt(5))
        nn.init.zeros_(self.B)

        for p in self.base.parameters():
            p.requires_grad = False

    def forward(self, x):
        base_out = self.base(x)

        a = self.drop(x) @ self.A.t()
        delta = a @ self.B.t()

        return base_out + self.scale * delta


class SpikeLoRALinear(nn.Module):
    def __init__(self, base: nn.Linear, r=8, alpha=16, Vtheta=0.05, dropout=0.0):
        super().__init__()

        self.base = base
        self.r = r
        self.alpha = alpha
        self.scale = alpha / r
        self.drop = nn.Dropout(dropout)

        in_dim = base.in_features
        out_dim = base.out_features

        self.A = nn.Parameter(torch.zeros(r, in_dim))
        self.B = nn.Parameter(torch.zeros(out_dim, r))

        nn.init.kaiming_uniform_(self.A, a=math.sqrt(5))
        nn.init.zeros_(self.B)

        for p in self.base.parameters():
            p.requires_grad = False

        self.gate = neuron.LIFNode(
            v_threshold=Vtheta,
            surrogate_function=surrogate.Sigmoid(),
            detach_reset=True
        )

        self.last_sparsity_pct = None

    def forward(self, x):
        functional.reset_net(self.gate)

        base_out = self.base(x)

        a = self.drop(x) @ self.A.t()
        g = self.gate(a)
        a_tilde = g * a

        with torch.no_grad():
            self.last_sparsity_pct = float((g == 0).float().mean().item() * 100.0)

        delta = a_tilde @ self.B.t()

        return base_out + self.scale * delta


def freeze_module(m: nn.Module):
    for p in m.parameters():
        p.requires_grad = False


def unfreeze_module(m: nn.Module):
    for p in m.parameters():
        p.requires_grad = True


class SpikingTCN_Adapters(nn.Module):
    def __init__(self, base_model: nn.Module, peft="lora", r=8, alpha=16, Vtheta=0.05):
        super().__init__()

        assert hasattr(base_model, "head"), "SpikingTCN must have .head"

        self.base = base_model
        self.peft = peft

        base_head = self.base.head

        if peft == "lora":
            self.base.head = LoRALinear(base_head, r=r, alpha=alpha, dropout=0.0)
        elif peft == "spikelora":
            self.base.head = SpikeLoRALinear(base_head, r=r, alpha=alpha, Vtheta=Vtheta, dropout=0.0)
        else:
            raise ValueError("peft must be 'lora' or 'spikelora'")

        freeze_module(self.base)
        unfreeze_module(self.base.head)

        for m in self.base.modules():
            if isinstance(m, nn.LayerNorm):
                for p in m.parameters():
                    p.requires_grad = True

    def forward(self, x):
        return self.base(x)

    def get_spikelora_sparsity(self):
        if hasattr(self.base.head, "last_sparsity_pct"):
            return self.base.head.last_sparsity_pct
        return None


# Quick shape test
B, L, Fdim, K = 8, 96, 10, 5
x = torch.randn(B, L, Fdim).to(device)
m = SpikingTCN(Fdim, K).to(device)
y = m(x)
print("SpikingTCN output shape:", y.shape)

# ===============================
# Cell 5: Training Utilities
# Restored AdamW + early stopping + stats
# ===============================

import time
import torch
import torch.nn as nn
from spikingjelly.activation_based import functional


def set_seed(seed=0):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def count_trainable_params(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)


def count_total_params(model):
    return sum(p.numel() for p in model.parameters())


def _to_device(x):
    if torch.is_tensor(x):
        return x.float().to(device)
    return torch.from_numpy(x).float().to(device)


def reset_snn_state(model):
    try:
        functional.reset_net(model)
    except Exception:
        pass


def train_one_epoch(model, loader, optim):
    model.train()

    crit = nn.MSELoss()
    total = 0.0

    for xb, yb in loader:
        xb = _to_device(xb)
        yb = _to_device(yb)

        reset_snn_state(model)

        optim.zero_grad(set_to_none=True)

        pred = model(xb)

        loss = crit(pred, yb)
        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        optim.step()

        total += loss.item() * xb.size(0)

        reset_snn_state(model)

    return total / len(loader.dataset)


@torch.no_grad()
def eval_model(model, loader):
    model.eval()

    preds, trues = [], []

    for xb, yb in loader:
        xb = _to_device(xb)
        yb = _to_device(yb)

        reset_snn_state(model)

        pred = model(xb)

        preds.append(pred.detach())
        trues.append(yb.detach())

        reset_snn_state(model)

    preds = torch.cat(preds, dim=0)
    trues = torch.cat(trues, dim=0)

    m = eval_metrics(trues, preds)

    return m["rmse"], m["mae"], m["smape"]


def fit(model, train_loader, val_loader, lr=1e-3, wd=1e-4, max_epochs=30, patience=10):
    optim = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=lr,
        weight_decay=wd
    )

    best_rmse = float("inf")
    best_state = None
    best_epoch = 0
    bad = 0

    t0 = time.time()

    for ep in range(1, max_epochs + 1):
        train_loss = train_one_epoch(model, train_loader, optim)

        val_rmse, val_mae, val_smape = eval_model(model, val_loader)

        print(
            f"Epoch {ep}/{max_epochs} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Val RMSE: {val_rmse:.4f}"
        )

        if val_rmse < best_rmse:
            best_rmse = val_rmse
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in model.state_dict().items()
            }
            best_epoch = ep
            bad = 0
        else:
            bad += 1

        if bad >= patience:
            print(f"Early stopping at epoch {ep}. Best epoch={best_epoch}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)

    reset_snn_state(model)

    return model, {
        "best_epoch": best_epoch,
        "best_val_rmse": best_rmse,
        "train_time_sec": time.time() - t0,
        "trainable_params": count_trainable_params(model),
        "total_params": count_total_params(model),
    }

# ===============================
# Cell 6: E1 run_one()
# Restored old string-based procedure
# ===============================

def run_one(
    task_id,
    model_name,
    lookback,
    horizons,
    seed=0,
    batch_size=128,
    max_epochs=30,
    spkT=8,
    r=8,
    alpha=16,
    Vtheta=0.05,
    pretrain_epochs=20,
    adapt_epochs=20,
    lr_full=1e-3,
    lr_adapt=5e-3
):
    set_seed(seed)

    df, cfg = load_df(task_id)

    X, Y = make_supervised(
        df,
        cfg["time_col"],
        cfg["target_col"],
        lookback,
        horizons,
        add_calendar=True
    )

    (Xtr, Ytr), (Xva, Yva), (Xte, Yte) = chronological_split(
        X,
        Y,
        train_ratio=0.7,
        val_ratio=0.1
    )

    Xtr, Xva, Xte, _ = standardize_fit_transform(Xtr, Xva, Xte)

    train_loader = DataLoader(
        WindowDataset(Xtr, Ytr),
        batch_size=batch_size,
        shuffle=True
    )

    val_loader = DataLoader(
        WindowDataset(Xva, Yva),
        batch_size=batch_size,
        shuffle=False
    )

    test_loader = DataLoader(
        WindowDataset(Xte, Yte),
        batch_size=batch_size,
        shuffle=False
    )

    F = Xtr.shape[-1]
    K = Ytr.shape[-1]

    sp_spars = ""

    if model_name == "mlp":
        model = MLPBaseline(lookback, F, K).to(device)
        model, stats = fit(
            model,
            train_loader,
            val_loader,
            max_epochs=max_epochs,
            lr=lr_full
        )

    elif model_name == "lstm":
        model = RNNBaseline("lstm", F, K).to(device)
        model, stats = fit(
            model,
            train_loader,
            val_loader,
            max_epochs=max_epochs,
            lr=lr_full
        )

    elif model_name == "gru":
        model = RNNBaseline("gru", F, K).to(device)
        model, stats = fit(
            model,
            train_loader,
            val_loader,
            max_epochs=max_epochs,
            lr=lr_full
        )

    elif model_name == "tcn":
        model = TCNBaseline(F, K).to(device)
        model, stats = fit(
            model,
            train_loader,
            val_loader,
            max_epochs=max_epochs,
            lr=lr_full
        )

    elif model_name == "patchtst":
        model = PatchTST(F, K).to(device)
        model, stats = fit(
            model,
            train_loader,
            val_loader,
            max_epochs=max_epochs,
            lr=lr_full
        )

    elif model_name == "snn_tcn":
        model = SpikingTCN(F, K, T=spkT).to(device)
        model, stats = fit(
            model,
            train_loader,
            val_loader,
            max_epochs=max_epochs,
            lr=lr_full
        )

    elif model_name in ["snn_tcn_lora", "snn_tcn_spikelora"]:
        base = SpikingTCN(F, K, T=spkT).to(device)

        base, stats_pre = fit(
            base,
            train_loader,
            val_loader,
            max_epochs=pretrain_epochs,
            lr=lr_full
        )

        peft_kind = "lora" if model_name == "snn_tcn_lora" else "spikelora"

        model = SpikingTCN_Adapters(
            base,
            peft=peft_kind,
            r=r,
            alpha=alpha,
            Vtheta=Vtheta
        ).to(device)

        model, stats = fit(
            model,
            train_loader,
            val_loader,
            max_epochs=adapt_epochs,
            lr=lr_adapt
        )

        stats["train_time_sec"] += stats_pre["train_time_sec"]

        if hasattr(model, "get_spikelora_sparsity"):
            sp = model.get_spikelora_sparsity()
            sp_spars = "" if sp is None else sp

    else:
        raise ValueError(f"Unknown model: {model_name}")

    test_rmse, test_mae, test_smape = eval_model(model, test_loader)

    print(
        f"Test RMSE: {test_rmse:.4f} | "
        f"MAE: {test_mae:.4f} | "
        f"SMAPE: {test_smape:.4f}"
    )

    return {
        "task": task_id,
        "model": model_name,
        "seed": seed,
        "lookback": lookback,
        "horizons": str(horizons),
        "test_rmse": test_rmse,
        "test_mae": test_mae,
        "test_smape": test_smape,
        "train_time_sec": stats["train_time_sec"],
        "trainable_params": stats["trainable_params"],
        "total_params": stats["total_params"],
        "trainable_ratio": stats["trainable_params"] / max(1, stats["total_params"]),
        "spikelora_sparsity_pct": sp_spars,
    }

# ===============================
# Cell 7: E1 — Backbone Sanity Check for CAEPIA Paper
# Purpose: show SpikeLoRA-X preserves forecasting performance.
# Not the main novelty.
# ===============================

RUN_E1_SANITY = True

if RUN_E1_SANITY:
    tasks = ["SR", "WP"]        # CAEPIA-focused: solar + optional wind power reliability
    models = ["lstm", "tcn", "snn_tcn", "snn_tcn_spikelora"]
    seeds = [0]                 # one seed is enough for sanity check

    lookback = 96
    horizons = [1, 2, 4, 8, 24]

    batch_size = 128
    max_epochs = 10             # reduced runtime
    spkT = 4

    E1_results = []

    for task in tasks:
        for model_name in models:
            for seed in seeds:
                print(f"\n[E1 sanity] task={task}, model={model_name}, seed={seed}")

                out = run_one(
                    task_id=task,
                    model_name=model_name,
                    lookback=lookback,
                    horizons=horizons,
                    seed=seed,
                    batch_size=batch_size,
                    max_epochs=max_epochs,
                    spkT=spkT,
                    r=8,
                    alpha=16,
                    Vtheta=0.05,
                    pretrain_epochs=8,
                    adapt_epochs=8,
                    lr_full=1e-3,
                    lr_adapt=5e-3
                )

                E1_results.append(out)

    E1_df = pd.DataFrame(E1_results)
    E1_df.to_csv("E1_backbone_sanity_caepea.csv", index=False)

    E1_summary = (
        E1_df
        .groupby(["task", "model"])
        .agg(
            test_rmse_mean=("test_rmse", "mean"),
            test_rmse_std=("test_rmse", "std"),
            test_mae_mean=("test_mae", "mean"),
            test_mae_std=("test_mae", "std"),
            test_smape_mean=("test_smape", "mean"),
            test_smape_std=("test_smape", "std"),
            trainable_ratio_mean=("trainable_ratio", "mean"),
            train_time_sec_mean=("train_time_sec", "mean"),
        )
        .reset_index()
    )

    E1_summary.to_csv("E1_backbone_sanity_summary_caepea.csv", index=False)
    print(E1_summary)

# ===============================
# Cell 8: Optional E2 — Compact Few-Shot Reference
# Purpose: supporting evidence only, not main CAEPIA novelty.
# ===============================

RUN_E2_COMPACT = False

if RUN_E2_COMPACT:
    tasks = ["SR"]
    seeds = [0]
    fractions = [0.1, 0.2]

    lookback = 96
    horizons = [1, 2, 4, 8, 24]

    spkT = 8
    r = 8
    alpha = 16
    Vtheta = 0.05

    batch_size = 128

    pretrain_epochs = 10
    adapt_epochs = 8

    lr_full = 1e-3
    lr_fullft = 1e-3
    lr_peft = 5e-3

    E2_results = []

    for task in tasks:
        for seed in seeds:
            print(f"\n[E2 compact] Pretraining base for task={task}, seed={seed}")

            base_state, splits, (F, K), pre_stats = pretrain_base(
                task_id=task,
                lookback=lookback,
                horizons=horizons,
                seed=seed,
                spkT=spkT,
                batch_size=batch_size,
                max_epochs=pretrain_epochs,
                lr=lr_full
            )

            Xtr, Ytr, Xva, Yva, Xte, Yte = splits

            for frac in fractions:
                train_loader, val_loader, test_loader, n_fs = make_fewshot_loaders(
                    Xtr, Ytr, Xva, Yva, Xte, Yte, frac, batch_size
                )

                for mode in ["fullft", "lora", "spikelora"]:
                    lr_mode = lr_fullft if mode == "fullft" else lr_peft

                    out = adapt_and_eval_e2(
                        base_state=base_state,
                        F=F,
                        K=K,
                        spkT=spkT,
                        mode=mode,
                        loaders=(train_loader, val_loader, test_loader),
                        r=r,
                        alpha=alpha,
                        Vtheta=Vtheta,
                        adapt_epochs=adapt_epochs,
                        lr_adapt=lr_mode
                    )

                    out.update({
                        "task": task,
                        "seed": seed,
                        "frac": frac,
                        "n_train_windows": n_fs,
                        "mode": mode,
                        "pretrain_time_sec": pre_stats["train_time_sec"]
                    })

                    E2_results.append(out)

                    print(
                        task, seed, frac, mode,
                        "RMSE", round(out["test_rmse"], 4),
                        "MAE", round(out["test_mae"], 4),
                        "SMAPE", round(out["test_smape"], 4),
                        "spars", out["spikelora_sparsity_pct"]
                    )

    E2_df = pd.DataFrame(E2_results)
    E2_df.to_csv("E2_compact_fewshot_reference_caepea.csv", index=False)

    E2_summary = (
        E2_df
        .groupby(["task", "mode", "frac"])
        .agg(
            rmse_mean=("test_rmse", "mean"),
            rmse_std=("test_rmse", "std"),
            mae_mean=("test_mae", "mean"),
            mae_std=("test_mae", "std"),
            smape_mean=("test_smape", "mean"),
            smape_std=("test_smape", "std"),
            trainable_ratio_mean=("trainable_ratio", "mean"),
            train_time_mean=("train_time_sec", "mean"),
            sparsity_mean=("spikelora_sparsity_pct", lambda x: pd.to_numeric(x, errors="coerce").mean())
        )
        .reset_index()
    )

    E2_summary.to_csv("E2_compact_fewshot_summary_caepea.csv", index=False)
    print(E2_summary)

# ===============================
# Cell 9: Optional E3 — Cross-Domain Limitation Analysis
# Purpose: limitation evidence only, not main contribution.
# ===============================

RUN_E3_LIMITATION = False

if RUN_E3_LIMITATION:
    tasks = ["SR", "WS", "WP", "EC"]
    seeds = [0]
    fractions = (0.1,)

    lookback = 96
    horizons = [1, 2, 4, 8, 24]

    spkT = 8
    batch_size = 128

    pretrain_epochs = 5
    adapt_epochs = 5

    r = 8
    alpha = 16
    Vtheta = 0.05

    E3_all = []

    target = "SR"
    sources = ["WS", "WP", "EC"]

    for seed in seeds:
        out = run_E3_one_target(
            target_task=target,
            source_tasks=sources,
            lookback=lookback,
            horizons=horizons,
            seed=seed,
            spkT=spkT,
            batch_size=batch_size,
            pretrain_epochs=pretrain_epochs,
            adapt_epochs=adapt_epochs,
            lr_full=1e-3,
            lr_fullft=1e-3,
            lr_peft=5e-3,
            r=r,
            alpha=alpha,
            Vtheta=Vtheta,
            fractions=fractions
        )

        E3_all.extend(out)

    E3_df = pd.DataFrame(E3_all)
    E3_df.to_csv("E3_limitation_analysis_caepea.csv", index=False)

    E3_summary = (
        E3_df
        .groupby(["target", "mode", "frac"])
        .agg(
            rmse_mean=("test_rmse", "mean"),
            rmse_std=("test_rmse", "std"),
            mae_mean=("test_mae", "mean"),
            mae_std=("test_mae", "std"),
            smape_mean=("test_smape", "mean"),
            smape_std=("test_smape", "std"),
            trainable_ratio_mean=("trainable_ratio", "mean"),
            sparsity_mean=("spikelora_sparsity_pct", lambda x: pd.to_numeric(x, errors="coerce").mean())
        )
        .reset_index()
    )

    E3_summary.to_csv("E3_limitation_summary_caepea.csv", index=False)
    print(E3_summary)

# ===============================
# Cell 10: Visualization & CSV/PNG Export
# Corrected for restored E1/E2/E3 summaries
# ===============================

import os
import pandas as pd
import matplotlib.pyplot as plt

OUTPUT_DIR = "spikelora_x_outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)


def save_results_csv(df, filename):
    """
    Save a dataframe as CSV and download it in Colab.
    """
    path = os.path.join(OUTPUT_DIR, filename)
    df.to_csv(path, index=False)
    print(f"Saved: {path}")

    try:
        from google.colab import files
        files.download(path)
    except Exception:
        pass

    return path


def save_figure(filename, dpi=300):
    """
    Save current matplotlib figure and download it in Colab.
    """
    path = os.path.join(OUTPUT_DIR, filename)
    plt.savefig(path, dpi=dpi, bbox_inches="tight")
    print(f"Saved: {path}")

    try:
        from google.colab import files
        files.download(path)
    except Exception:
        pass

    return path


def export_all_results():
    """
    Export available E1/E2/E3 dataframes if they exist.
    """
    exported = []

    if "E1_df" in globals():
        exported.append(save_results_csv(E1_df, "E1_results_restored_protocol.csv"))

    if "E1_summary" in globals():
        exported.append(save_results_csv(E1_summary, "E1_summary_restored_protocol.csv"))

    if "E2_df" in globals():
        exported.append(save_results_csv(E2_df, "E2_fewshot_results_restored_protocol.csv"))

    if "E2_summary" in globals():
        exported.append(save_results_csv(E2_summary, "E2_summary_restored_protocol.csv"))

    if "E3_df" in globals():
        exported.append(save_results_csv(E3_df, "E3_leave_one_task_out_aligned_restored_protocol.csv"))

    if "E3_summary" in globals():
        exported.append(save_results_csv(E3_summary, "E3_summary_leave_one_task_out_aligned_restored_protocol.csv"))

    if not exported:
        print("No result dataframes found yet. Run E1/E2/E3 first.")

    return exported


def plot_e1_bar(task, metric="test_rmse_mean", save=True):
    """
    Plot E1 mean performance per model for one task.
    Requires E1_summary.
    """
    if "E1_summary" not in globals():
        raise RuntimeError("E1_summary not found. Run E1 first.")

    sub = E1_summary[E1_summary["task"] == task].copy()

    if sub.empty:
        raise ValueError(f"No E1 results found for task={task}")

    sub = sub.sort_values(metric)

    plt.figure(figsize=(9, 5))
    plt.bar(sub["model"], sub[metric])
    plt.xticks(rotation=45, ha="right")
    plt.ylabel(metric)
    plt.title(f"E1 In-Domain Benchmark - {task}")
    plt.grid(axis="y", alpha=0.3)
    plt.tight_layout()

    if save:
        save_figure(f"E1_{task}_{metric}.png")

    plt.show()


def plot_e2(task, metric="rmse_mean", save=True):
    """
    Plot E2 few-shot adaptation curves.
    Requires E2_summary.
    """
    if "E2_summary" not in globals():
        raise RuntimeError("E2_summary not found. Run E2 first.")

    sub = E2_summary[E2_summary["task"] == task].copy()

    if sub.empty:
        raise ValueError(f"No E2 results found for task={task}")

    plt.figure(figsize=(7, 5))

    for mode in ["fullft", "lora", "spikelora"]:
        m = sub[sub["mode"] == mode].sort_values("frac")

        if not m.empty:
            plt.plot(
                m["frac"],
                m[metric],
                marker="o",
                linewidth=2,
                label=mode
            )

    plt.xlabel("Few-shot fraction")
    plt.ylabel(metric)
    plt.title(f"E2 Few-Shot Adaptation - {task}")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    if save:
        save_figure(f"E2_{task}_{metric}.png")

    plt.show()


def plot_e3(target, metric="rmse_mean", save=True):
    """
    Plot E3 leave-one-task-out cross-domain transfer curves.
    Requires E3_summary.
    """
    if "E3_summary" not in globals():
        raise RuntimeError("E3_summary not found. Run E3 first.")

    sub = E3_summary[E3_summary["target"] == target].copy()

    if sub.empty:
        raise ValueError(f"No E3 results found for target={target}")

    plt.figure(figsize=(7, 5))

    for mode in ["fullft", "lora", "spikelora"]:
        m = sub[sub["mode"] == mode].sort_values("frac")

        if not m.empty:
            plt.plot(
                m["frac"],
                m[metric],
                marker="o",
                linewidth=2,
                label=mode
            )

    plt.xlabel("Few-shot fraction")
    plt.ylabel(metric)
    plt.title(f"E3 Cross-Domain Transfer - Target {target}")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    if save:
        save_figure(f"E3_{target}_{metric}.png")

    plt.show()


def plot_all_e2(metric="rmse_mean"):
    """
    Generate E2 plots for all available tasks.
    """
    if "E2_summary" not in globals():
        raise RuntimeError("E2_summary not found. Run E2 first.")

    for task in sorted(E2_summary["task"].unique()):
        plot_e2(task, metric=metric, save=True)


def plot_all_e3(metric="rmse_mean"):
    """
    Generate E3 plots for all available targets.
    """
    if "E3_summary" not in globals():
        raise RuntimeError("E3_summary not found. Run E3 first.")

    for target in sorted(E3_summary["target"].unique()):
        plot_e3(target, metric=metric, save=True)


def make_latex_ready_tables():
    """
    Create compact CSV tables suitable for LaTeX.
    """
    tables = {}

    if "E1_summary" in globals():
        e1_latex = E1_summary.copy()
        e1_latex["RMSE"] = e1_latex.apply(
            lambda r: f"{r['test_rmse_mean']:.3f} ± {r['test_rmse_std']:.3f}",
            axis=1
        )
        e1_latex["MAE"] = e1_latex.apply(
            lambda r: f"{r['test_mae_mean']:.3f} ± {r['test_mae_std']:.3f}",
            axis=1
        )
        e1_latex["SMAPE"] = e1_latex.apply(
            lambda r: f"{r['test_smape_mean']:.3f} ± {r['test_smape_std']:.3f}",
            axis=1
        )
        e1_latex = e1_latex[["task", "model", "RMSE", "MAE", "SMAPE", "trainable_ratio_mean"]]
        tables["E1_latex"] = e1_latex
        save_results_csv(e1_latex, "Table_E1_latex_ready.csv")

    if "E2_summary" in globals():
        e2_latex = E2_summary.copy()
        e2_latex["RMSE"] = e2_latex.apply(
            lambda r: f"{r['rmse_mean']:.3f} ± {r['rmse_std']:.3f}",
            axis=1
        )
        e2_latex["MAE"] = e2_latex.apply(
            lambda r: f"{r['mae_mean']:.3f} ± {r['mae_std']:.3f}",
            axis=1
        )
        e2_latex["SMAPE"] = e2_latex.apply(
            lambda r: f"{r['smape_mean']:.3f} ± {r['smape_std']:.3f}",
            axis=1
        )
        keep_cols = ["task", "mode", "frac", "RMSE", "MAE", "SMAPE", "trainable_ratio_mean"]
        if "sparsity_mean" in e2_latex.columns:
            keep_cols.append("sparsity_mean")
        e2_latex = e2_latex[keep_cols]
        tables["E2_latex"] = e2_latex
        save_results_csv(e2_latex, "Table_E2_latex_ready.csv")

    if "E3_summary" in globals():
        e3_latex = E3_summary.copy()
        e3_latex["RMSE"] = e3_latex.apply(
            lambda r: f"{r['rmse_mean']:.3f} ± {r['rmse_std']:.3f}",
            axis=1
        )
        e3_latex["MAE"] = e3_latex.apply(
            lambda r: f"{r['mae_mean']:.3f} ± {r['mae_std']:.3f}",
            axis=1
        )
        e3_latex["SMAPE"] = e3_latex.apply(
            lambda r: f"{r['smape_mean']:.3f} ± {r['smape_std']:.3f}",
            axis=1
        )
        keep_cols = ["target", "mode", "frac", "RMSE", "MAE", "SMAPE", "trainable_ratio_mean"]
        if "sparsity_mean" in e3_latex.columns:
            keep_cols.append("sparsity_mean")
        e3_latex = e3_latex[keep_cols]
        tables["E3_latex"] = e3_latex
        save_results_csv(e3_latex, "Table_E3_latex_ready.csv")

    if not tables:
        print("No summaries found. Run E1/E2/E3 first.")

    return tables

# -------------------------------
# Cell 10: Execution Notes
# -------------------------------
# E1: Run in-domain for all datasets & baseline models
# E2: Run few-shot adaptation for fractions 0.1/0.2/0.5
# E3: Run cross-domain transfer for selected task pairs
# Save CSVs and figures for LaTeX
# Use Vtheta=0.05 for SpikeLoRA to prevent over-suppression

# ===============================
# Cell 11: Spike-Attribution Module
# Occlusion-based horizon-wise attribution for SpikeLoRA-X
# ===============================

import numpy as np
import torch
import matplotlib.pyplot as plt


def get_feature_names_for_task(task_id, lookback=96, horizons=[1,2,4,8,24]):
    """
    Returns the feature names after make_supervised(add_calendar=True).
    Useful for attribution heatmaps.
    """
    df, cfg = load_df(task_id)

    base_features = [c for c in df.columns if c != cfg["time_col"]]
    feature_names = base_features + ["hour", "dayofweek", "month"]

    return feature_names


def compute_spike_attribution(
    model,
    X_input,
    horizon_labels=None,
    max_samples=512,
    device=device,
    occlusion_value=0.0,
    batch_size=128,
    normalize=True
):
    """
    Computes horizon-wise feature attribution for SNN forecasting using
    occlusion sensitivity.

    Method:
    - Run the trained model once to obtain baseline predictions.
    - For each input feature f, replace that feature over the full lookback
      window with an occlusion value.
    - Measure the absolute prediction change at each forecast horizon.
    - Return a heatmap with shape [num_features, num_horizons].

    For the standardized inputs used in this script, occlusion_value=0.0
    corresponds to replacing a feature by its training-set mean. This matches
    the SpikeLoRA-X manuscript definition of occlusion-based horizon-wise
    attribution and avoids relying on direct input gradients through hard
    threshold spike encoders.

    Input:
        X_input: numpy array or tensor with shape [N, L, F]
        horizon_labels: optional labels for horizons; kept for API compatibility
        max_samples: maximum number of samples used for attribution
        occlusion_value: scalar replacement value, or length-F array of values
        batch_size: batch size used for repeated forward passes
        normalize: if True, normalize each horizon column to [0, 1]

    Output:
        heatmap: numpy array with shape [F, K]
                 heatmap[f, k] = mean_i |y_hat_i,k - y_hat_i,k(-f)|
    """

    del horizon_labels  # labels are used by the plotting function, not here

    model.eval()
    reset_snn_state(model)

    if isinstance(X_input, np.ndarray):
        X_cpu = torch.tensor(X_input, dtype=torch.float32)
    else:
        X_cpu = X_input.detach().clone().float().cpu()

    if X_cpu.ndim != 3:
        raise ValueError(
            f"X_input must have shape [N, L, F], but got {tuple(X_cpu.shape)}"
        )

    if max_samples is not None and X_cpu.shape[0] > max_samples:
        X_cpu = X_cpu[:max_samples].clone()
    else:
        X_cpu = X_cpu.clone()

    N, L, Fdim = X_cpu.shape

    if batch_size is None or batch_size <= 0:
        batch_size = N

    if np.isscalar(occlusion_value):
        occlusion_values = np.full(Fdim, float(occlusion_value), dtype=np.float32)
    else:
        occlusion_values = np.asarray(occlusion_value, dtype=np.float32).reshape(-1)
        if occlusion_values.shape[0] != Fdim:
            raise ValueError(
                "occlusion_value must be a scalar or a length-F array, "
                f"but got length {occlusion_values.shape[0]} for F={Fdim}"
            )

    @torch.no_grad()
    def _predict_tensor_batches(X_tensor_cpu):
        preds = []
        for start_idx in range(0, X_tensor_cpu.shape[0], batch_size):
            xb = X_tensor_cpu[start_idx:start_idx + batch_size].to(device)
            reset_snn_state(model)
            pred = model(xb)
            preds.append(pred.detach().cpu())
            reset_snn_state(model)
        return torch.cat(preds, dim=0)

    baseline_preds = _predict_tensor_batches(X_cpu)  # [N, K]
    K = baseline_preds.shape[-1]

    heatmap = np.zeros((Fdim, K), dtype=np.float32)

    for f_idx in range(Fdim):
        X_occ = X_cpu.clone()
        X_occ[:, :, f_idx] = float(occlusion_values[f_idx])

        occ_preds = _predict_tensor_batches(X_occ)  # [N, K]
        attr_f = (baseline_preds - occ_preds).abs().mean(dim=0).numpy()
        heatmap[f_idx, :] = attr_f

    if normalize:
        denom = heatmap.max(axis=0, keepdims=True)
        heatmap = heatmap / (denom + 1e-8)

    reset_snn_state(model)

    return heatmap

def compute_spike_activity_summary(model, X_input, max_samples=512, device=device):
    """
    Captures average spike activity from LIFNode modules.
    This is useful as an explainability/energy proxy.

    Returns:
        dictionary with layer names and average spike rates.
    """

    model.eval()
    reset_snn_state(model)

    if isinstance(X_input, np.ndarray):
        X = torch.tensor(X_input, dtype=torch.float32)
    else:
        X = X_input.detach().clone().float()

    if X.shape[0] > max_samples:
        X = X[:max_samples]

    X = X.to(device)

    spike_rates = {}
    hooks = []

    def make_hook(name):
        def hook(module, inputs, output):
            if torch.is_tensor(output):
                spike_rates[name] = float((output.detach() > 0).float().mean().cpu().item())
        return hook

    for name, module in model.named_modules():
        if isinstance(module, neuron.LIFNode):
            hooks.append(module.register_forward_hook(make_hook(name)))

    with torch.no_grad():
        _ = model(X)

    for h in hooks:
        h.remove()

    reset_snn_state(model)

    return spike_rates

# ===============================
# Cell 12: Physics-Informed Regularization
# Corrected loss: compares preds with targets, not preds with preds
# ===============================

import torch
import torch.nn as nn


def physics_informed_loss(
    preds,
    targets,
    upper_limits=None,
    lower_limits=None,
    lambda_phys=0.01,
    base_loss_fn=None
):
    """
    Physics-informed regression loss.

    Loss = MSE(preds, targets)
           + lambda_phys * violation penalty

    upper_limits:
        Tensor/scalar with maximum physically allowed value.
        Example:
            - PV GHI upper bound: 1200 W/m2
            - Wind power upper bound: turbine rated power
            - Electricity consumption upper bound: historical operational max

    lower_limits:
        Tensor/scalar with minimum physically allowed value.
        Usually 0 for GHI, wind speed, wind power, and consumption.
    """

    if base_loss_fn is None:
        base_loss_fn = nn.MSELoss()

    base_loss = base_loss_fn(preds, targets)

    penalty = torch.tensor(0.0, device=preds.device)

    if upper_limits is not None:
        if not torch.is_tensor(upper_limits):
            upper_limits = torch.tensor(upper_limits, dtype=preds.dtype, device=preds.device)
        else:
            upper_limits = upper_limits.to(preds.device).type_as(preds)

        penalty = penalty + torch.clamp(preds - upper_limits, min=0.0).pow(2).mean()

    if lower_limits is not None:
        if not torch.is_tensor(lower_limits):
            lower_limits = torch.tensor(lower_limits, dtype=preds.dtype, device=preds.device)
        else:
            lower_limits = lower_limits.to(preds.device).type_as(preds)

        penalty = penalty + torch.clamp(lower_limits - preds, min=0.0).pow(2).mean()

    return base_loss + lambda_phys * penalty


def get_physical_limits_from_training(Ytr, task_id, safety_factor=1.05):
    """
    Builds simple operational physical limits from training targets.

    This is not a perfect physics model, but it is safe and practical:
    - lower bound = 0
    - upper bound = 1.05 * max training target per horizon

    For the paper, describe it as 'operational physical plausibility constraint'
    unless you use a true turbine/PV curve.
    """

    Ytr_np = np.asarray(Ytr)

    lower = np.zeros((1, Ytr_np.shape[1]), dtype=np.float32)
    upper = safety_factor * np.nanmax(Ytr_np, axis=0, keepdims=True).astype(np.float32)

    # Optional stronger fixed caps
    if task_id == "SR":
        # GHI rarely exceeds around 1200 W/m2 physically
        upper = np.minimum(upper, 1200.0)

    if task_id == "WS":
        # Wind speed lower bound already 0; upper remains data-derived
        pass

    if task_id == "WP":
        # Wind turbine active power cannot be negative.
        # Upper remains data-derived unless rated power is known.
        pass

    if task_id == "EC":
        # Consumption cannot be negative.
        pass

    return lower, upper


def count_physics_violations(preds, lower_limits=None, upper_limits=None):
    """
    Counts fraction of predictions violating physical/operational limits.
    """

    if torch.is_tensor(preds):
        p = preds.detach().cpu().numpy()
    else:
        p = np.asarray(preds)

    violations = np.zeros_like(p, dtype=bool)

    if lower_limits is not None:
        lo = np.asarray(lower_limits)
        violations |= p < lo

    if upper_limits is not None:
        hi = np.asarray(upper_limits)
        violations |= p > hi

    return 100.0 * violations.mean()

# ===============================
# Optional: Physics-aware fine-tuning
# ===============================

def train_one_epoch_physics(
    model,
    loader,
    optim,
    lower_limits,
    upper_limits,
    lambda_phys=0.01
):
    model.train()

    total = 0.0

    lower_t = torch.tensor(lower_limits, dtype=torch.float32, device=device)
    upper_t = torch.tensor(upper_limits, dtype=torch.float32, device=device)

    for xb, yb in loader:
        xb = _to_device(xb)
        yb = _to_device(yb)

        reset_snn_state(model)

        optim.zero_grad(set_to_none=True)

        pred = model(xb)

        loss = physics_informed_loss(
            preds=pred,
            targets=yb,
            lower_limits=lower_t,
            upper_limits=upper_t,
            lambda_phys=lambda_phys
        )

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optim.step()

        total += loss.item() * xb.size(0)

        reset_snn_state(model)

    return total / len(loader.dataset)


def fit_physics(
    model,
    train_loader,
    val_loader,
    lower_limits,
    upper_limits,
    lr=1e-3,
    wd=1e-4,
    max_epochs=20,
    patience=7,
    lambda_phys=0.01
):
    optim = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=lr,
        weight_decay=wd
    )

    best_rmse = float("inf")
    best_state = None
    best_epoch = 0
    bad = 0

    for ep in range(1, max_epochs + 1):
        train_loss = train_one_epoch_physics(
            model=model,
            loader=train_loader,
            optim=optim,
            lower_limits=lower_limits,
            upper_limits=upper_limits,
            lambda_phys=lambda_phys
        )

        val_rmse, val_mae, val_smape = eval_model(model, val_loader)

        print(
            f"Epoch {ep}/{max_epochs} | "
            f"Physics Train Loss: {train_loss:.4f} | "
            f"Val RMSE: {val_rmse:.4f}"
        )

        if val_rmse < best_rmse:
            best_rmse = val_rmse
            best_state = {
                k: v.detach().cpu().clone()
                for k, v in model.state_dict().items()
            }
            best_epoch = ep
            bad = 0
        else:
            bad += 1

        if bad >= patience:
            print(f"Early stopping at epoch {ep}. Best epoch={best_epoch}")
            break

    if best_state is not None:
        model.load_state_dict(best_state)

    reset_snn_state(model)

    return model

# ===============================
# Cell 13: Spike-Attribution Visualization
# ===============================

def plot_spike_attribution(
    heatmap,
    feature_names=None,
    horizon_labels=None,
    title="Horizon-wise Spike Attribution",
    save_path=None
):
    heatmap = np.asarray(heatmap)

    if feature_names is None:
        feature_names = [f"f{i}" for i in range(heatmap.shape[0])]

    if horizon_labels is None:
        horizon_labels = [f"h{i}" for i in range(heatmap.shape[1])]

    plt.figure(figsize=(10, max(5, 0.35 * len(feature_names))))

    im = plt.imshow(heatmap, aspect="auto")
    plt.colorbar(im, label="Normalized occlusion attribution")

    plt.xticks(np.arange(len(horizon_labels)), horizon_labels)
    plt.yticks(np.arange(len(feature_names)), feature_names)

    plt.xlabel("Forecast horizon")
    plt.ylabel("Input feature")
    plt.title(title)

    plt.tight_layout()

    if save_path is not None:
        plt.savefig(save_path, dpi=300, bbox_inches="tight")
        print(f"Saved: {save_path}")

    plt.show()

# ===============================
# Cell 14: CAEPIA Main Experiment
# SpikeLoRA-X = SpikeLoRA backbone + explainability + responsible AI analysis
# ===============================

def prepare_task_data(task_id, lookback, horizons, batch_size=128):
    df, cfg = load_df(task_id)

    X, Y = make_supervised(
        df,
        cfg["time_col"],
        cfg["target_col"],
        lookback,
        horizons,
        add_calendar=True
    )

    (Xtr, Ytr), (Xva, Yva), (Xte, Yte) = chronological_split(
        X, Y, train_ratio=0.7, val_ratio=0.1
    )

    Xtr, Xva, Xte, scaler = standardize_fit_transform(Xtr, Xva, Xte)

    train_loader = DataLoader(
        WindowDataset(Xtr, Ytr),
        batch_size=batch_size,
        shuffle=True
    )

    val_loader = DataLoader(
        WindowDataset(Xva, Yva),
        batch_size=batch_size,
        shuffle=False
    )

    test_loader = DataLoader(
        WindowDataset(Xte, Yte),
        batch_size=batch_size,
        shuffle=False
    )

    F = Xtr.shape[-1]
    K = Ytr.shape[-1]

    return {
        "df": df,
        "cfg": cfg,
        "Xtr": Xtr,
        "Ytr": Ytr,
        "Xva": Xva,
        "Yva": Yva,
        "Xte": Xte,
        "Yte": Yte,
        "train_loader": train_loader,
        "val_loader": val_loader,
        "test_loader": test_loader,
        "F": F,
        "K": K,
        "scaler": scaler
    }


def train_spikelora_x_for_task(
    task_id,
    lookback=96,
    horizons=[1, 2, 4, 8, 24],
    seed=0,
    spkT=8,
    batch_size=128,
    pretrain_epochs=10,
    adapt_epochs=10,
    r=8,
    alpha=16,
    Vtheta=0.05,
    lr_full=1e-3,
    lr_adapt=5e-3
):
    """
    Trains the SpikeLoRA-X forecasting backbone:
    1. Pretrain SNN-TCN.
    2. Freeze backbone and adapt SpikeLoRA head.
    3. Return trained model and data splits for XAI/reliability analysis.
    """

    set_seed(seed)

    data = prepare_task_data(
        task_id=task_id,
        lookback=lookback,
        horizons=horizons,
        batch_size=batch_size
    )

    F = data["F"]
    K = data["K"]

    print(f"\n[SpikeLoRA-X] Pretraining base SNN-TCN for {task_id}")

    base = SpikingTCN(F, K, T=spkT).to(device)

    base, stats_pre = fit(
        base,
        data["train_loader"],
        data["val_loader"],
        max_epochs=pretrain_epochs,
        lr=lr_full
    )

    print(f"\n[SpikeLoRA-X] Adapting SpikeLoRA head for {task_id}")

    model = SpikingTCN_Adapters(
        base,
        peft="spikelora",
        r=r,
        alpha=alpha,
        Vtheta=Vtheta
    ).to(device)

    model, stats_adapt = fit(
        model,
        data["train_loader"],
        data["val_loader"],
        max_epochs=adapt_epochs,
        lr=lr_adapt
    )

    test_rmse, test_mae, test_smape = eval_model(model, data["test_loader"])

    sp_spars = model.get_spikelora_sparsity() if hasattr(model, "get_spikelora_sparsity") else None

    result = {
        "task": task_id,
        "seed": seed,
        "model": "spikelora_x",
        "test_rmse": test_rmse,
        "test_mae": test_mae,
        "test_smape": test_smape,
        "trainable_params": count_trainable_params(model),
        "total_params": count_total_params(model),
        "trainable_ratio": count_trainable_params(model) / max(1, count_total_params(model)),
        "spikelora_sparsity_pct": sp_spars,
        "pretrain_time_sec": stats_pre["train_time_sec"],
        "adapt_time_sec": stats_adapt["train_time_sec"]
    }

    print("\n[SpikeLoRA-X test]")
    print(result)

    return model, data, result


@torch.no_grad()
def predict_numpy(model, X, batch_size=128):
    loader = DataLoader(
        WindowDataset(X, np.zeros((len(X), 1), dtype=np.float32)),
        batch_size=batch_size,
        shuffle=False
    )

    preds = []

    model.eval()

    for xb, _ in loader:
        xb = _to_device(xb)
        reset_snn_state(model)
        pred = model(xb)
        preds.append(pred.detach().cpu())
        reset_snn_state(model)

    return torch.cat(preds, dim=0).numpy()


def topk_feature_masking_fidelity(
    model,
    Xte,
    Yte,
    feature_names,
    heatmap,
    top_k=3,
    random_repeats=5,
    batch_size=128,
    seed=0,
    mask_value=0.0
):
    """
    Tests whether the occlusion attribution is meaningful:
    - Mask top-k attributed features using mask_value. By default, mask_value
      is 0.0, which is the training-set mean after standardization.
    - Mask random-k features with the same procedure.
    - If top-k masking hurts more, the attribution has fidelity.
    """

    rng = np.random.default_rng(seed)

    original_preds = predict_numpy(model, Xte, batch_size=batch_size)
    original_rmse = rmse_np(Yte, original_preds)
    original_mae = mae_np(Yte, original_preds)
    original_smape = smape_np(Yte, original_preds)

    global_attr = heatmap.mean(axis=1)
    top_idx = np.argsort(global_attr)[::-1][:top_k]

    X_top = Xte.copy()
    X_top[:, :, top_idx] = mask_value

    top_preds = predict_numpy(model, X_top, batch_size=batch_size)
    top_rmse = rmse_np(Yte, top_preds)
    top_mae = mae_np(Yte, top_preds)
    top_smape = smape_np(Yte, top_preds)

    random_rmses = []
    random_maes = []
    random_smapes = []

    all_idx = np.arange(Xte.shape[-1])

    for _ in range(random_repeats):
        rand_idx = rng.choice(all_idx, size=top_k, replace=False)

        X_rand = Xte.copy()
        X_rand[:, :, rand_idx] = mask_value

        rand_preds = predict_numpy(model, X_rand, batch_size=batch_size)

        random_rmses.append(rmse_np(Yte, rand_preds))
        random_maes.append(mae_np(Yte, rand_preds))
        random_smapes.append(smape_np(Yte, rand_preds))

    random_rmse = float(np.mean(random_rmses))
    random_mae = float(np.mean(random_maes))
    random_smape = float(np.mean(random_smapes))

    fidelity = {
        "top_k": top_k,
        "top_features": ", ".join([feature_names[i] for i in top_idx]),
        "original_rmse": original_rmse,
        "topk_mask_rmse": top_rmse,
        "random_mask_rmse": random_rmse,
        "topk_rmse_increase": top_rmse - original_rmse,
        "random_rmse_increase": random_rmse - original_rmse,
        "fidelity_gain_rmse": (top_rmse - original_rmse) - (random_rmse - original_rmse),
        "original_mae": original_mae,
        "topk_mask_mae": top_mae,
        "random_mask_mae": random_mae,
        "original_smape": original_smape,
        "topk_mask_smape": top_smape,
        "random_mask_smape": random_smape,
    }

    return fidelity


def run_physics_violation_analysis(model, data, task_id, batch_size=128):
    """
    Post-hoc physical plausibility analysis.
    This does not change the model.
    """

    lower, upper = get_physical_limits_from_training(
        data["Ytr"],
        task_id=task_id,
        safety_factor=1.05
    )

    preds = predict_numpy(model, data["Xte"], batch_size=batch_size)

    violation_pct = count_physics_violations(
        preds,
        lower_limits=lower,
        upper_limits=upper
    )

    rmse = rmse_np(data["Yte"], preds)
    mae = mae_np(data["Yte"], preds)
    smape = smape_np(data["Yte"], preds)

    out = {
        "task": task_id,
        "rmse": rmse,
        "mae": mae,
        "smape": smape,
        "physical_violation_pct": violation_pct,
        "lower_limits": lower.tolist(),
        "upper_limits": upper.tolist()
    }

    return out


def run_caepea_main_experiment(
    tasks=("SR", "WP"),
    seed=0,
    lookback=96,
    horizons=[1, 2, 4, 8, 24],
    spkT=8,
    batch_size=128,
    pretrain_epochs=10,
    adapt_epochs=10,
    top_k=3
):
    """
    Main CAEPIA/CAEPEA experiment:
    - Train SpikeLoRA-X.
    - Generate occlusion-based horizon-wise attribution heatmap.
    - Run attribution fidelity masking.
    - Run physical plausibility analysis.
    - Save CSVs and figures.
    """

    os.makedirs("spikelora_x_outputs", exist_ok=True)

    horizon_labels = [f"h={h}" for h in horizons]

    backbone_results = []
    fidelity_results = []
    physics_results = []
    spike_activity_results = []

    trained_models = {}

    for task_id in tasks:
        print(f"\n===============================")
        print(f"Running CAEPIA main experiment for {task_id}")
        print(f"===============================")

        model, data, backbone_result = train_spikelora_x_for_task(
            task_id=task_id,
            lookback=lookback,
            horizons=horizons,
            seed=seed,
            spkT=spkT,
            batch_size=batch_size,
            pretrain_epochs=pretrain_epochs,
            adapt_epochs=adapt_epochs,
            r=8,
            alpha=16,
            Vtheta=0.05,
            lr_full=1e-3,
            lr_adapt=5e-3
        )

        trained_models[task_id] = model
        backbone_results.append(backbone_result)

        feature_names = get_feature_names_for_task(task_id)

        heatmap = compute_spike_attribution(
            model=model,
            X_input=data["Xte"][:512],
            horizon_labels=horizon_labels,
            max_samples=512,
            device=device,
            occlusion_value=0.0,
            batch_size=batch_size,
            normalize=True
        )

        heatmap_df = pd.DataFrame(
            heatmap,
            index=feature_names,
            columns=horizon_labels
        )

        heatmap_csv = f"spikelora_x_outputs/Attribution_heatmap_{task_id}.csv"
        heatmap_png = f"spikelora_x_outputs/Attribution_heatmap_{task_id}.png"

        heatmap_df.to_csv(heatmap_csv)

        plot_spike_attribution(
            heatmap,
            feature_names=feature_names,
            horizon_labels=horizon_labels,
            title=f"SpikeLoRA-X Occlusion-Based Horizon-wise Attribution — {task_id}",
            save_path=heatmap_png
        )

        fidelity = topk_feature_masking_fidelity(
            model=model,
            Xte=data["Xte"],
            Yte=data["Yte"],
            feature_names=feature_names,
            heatmap=heatmap,
            top_k=top_k,
            random_repeats=5,
            batch_size=batch_size,
            seed=seed
        )

        fidelity["task"] = task_id
        fidelity_results.append(fidelity)

        print("\n[Attribution fidelity]")
        print(fidelity)

        physics = run_physics_violation_analysis(
            model=model,
            data=data,
            task_id=task_id,
            batch_size=batch_size
        )

        physics_results.append(physics)

        print("\n[Physical plausibility]")
        print(physics)

        spike_activity = compute_spike_activity_summary(
            model,
            data["Xte"][:512],
            max_samples=512,
            device=device
        )

        spike_activity_row = {
            "task": task_id,
            **spike_activity
        }

        spike_activity_results.append(spike_activity_row)

        print("\n[Spike activity summary]")
        print(spike_activity_row)

    backbone_df = pd.DataFrame(backbone_results)
    fidelity_df = pd.DataFrame(fidelity_results)
    physics_df = pd.DataFrame(physics_results)
    spike_activity_df = pd.DataFrame(spike_activity_results)

    backbone_df.to_csv("spikelora_x_outputs/Table_backbone_sanity_caepea.csv", index=False)
    fidelity_df.to_csv("spikelora_x_outputs/Table_attribution_fidelity_caepea.csv", index=False)
    physics_df.to_csv("spikelora_x_outputs/Table_physics_plausibility_caepea.csv", index=False)
    spike_activity_df.to_csv("spikelora_x_outputs/Table_spike_activity_caepea.csv", index=False)

    print("\nSaved CAEPIA main outputs:")
    print("spikelora_x_outputs/Table_backbone_sanity_caepea.csv")
    print("spikelora_x_outputs/Table_attribution_fidelity_caepea.csv")
    print("spikelora_x_outputs/Table_physics_plausibility_caepea.csv")
    print("spikelora_x_outputs/Table_spike_activity_caepea.csv")

    try:
        from google.colab import files

        for f in [
            "spikelora_x_outputs/Table_backbone_sanity_caepea.csv",
            "spikelora_x_outputs/Table_attribution_fidelity_caepea.csv",
            "spikelora_x_outputs/Table_physics_plausibility_caepea.csv",
            "spikelora_x_outputs/Table_spike_activity_caepea.csv",
        ]:
            files.download(f)

    except Exception:
        pass

    return {
        "models": trained_models,
        "backbone_df": backbone_df,
        "fidelity_df": fidelity_df,
        "physics_df": physics_df,
        "spike_activity_df": spike_activity_df
    }

"""**Example usage after training a model**


"""

# ===============================
# Cell 15: Run Main CAEPIA Experiment
# ===============================

CAEPIA_RESULTS = run_caepea_main_experiment(
    tasks=("SR", "WP"),           # SR is essential; WP supports physics/reliability
    seed=0,
    lookback=96,
    horizons=[1, 2, 4, 8, 24],
    spkT=8,
    batch_size=128,
    pretrain_epochs=10,
    adapt_epochs=10,
    top_k=3
)

CAEPIA_RESULTS["backbone_df"]
